SELECT score_t_score.score            AS score_score,
       score_t_score.subject_id       AS score_subject_id,
       subject_xmlless.t_subject.id   AS score_subject_id,
       subject_xmlless.t_subject.name AS score_subject_name,
       xmlless.t_student.age,
       xmlless.t_student.birthday,
       xmlless.t_student.create_time,
       xmlless.t_student.detail,
       xmlless.t_student.education,
       xmlless.t_student.email,
       xmlless.t_student.favorites,
       xmlless.t_student.graduated,
       xmlless.t_student.id,
       xmlless.t_student.name,
       xmlless.t_student.nick_names,
       xmlless.t_student.phone_number,
       xmlless.t_student.sex,
       xmlless.t_student.state
FROM (SELECT * FROM xmlless.t_student LIMIT ?, ?) AS t_student
       LEFT JOIN t_score AS score_t_score ON score_t_score
